name: medical_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Core packages
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2

  # Network & API
  dio: ^5.7.0
  retrofit: ^4.4.1
  pretty_dio_logger: ^1.4.0

  # Code generation annotations
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

  # Localization & Internationalization
  easy_localization: ^3.0.7
  intl: ^0.19.0

  # UI
  flutter_svg: ^2.0.16
  flutter_native_splash: ^2.4.3
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generators
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  freezed: ^2.5.7
  retrofit_generator: ^9.1.5

  # Linting
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
